only source credentials to create the .cfg/{cluster-host} file
Fixup name for consistency of private repo and service endpoint in
namespace.

diff --git a/k8s-git-private-rc+svc-repo.yaml b/k8s-git-private-rc+svc-repo.yaml
--- a/k8s-git-private-rc+svc-repo.yaml
+++ b/k8s-git-private-rc+svc-repo.yaml
@@ -11,6 +11,7 @@ metadata:
   labels:
     app: k8s-git-repo
     version: v0.1
+    release: canary
 spec:
   replicas: 1
   selector:
@@ -21,6 +22,7 @@ spec:
       labels:
         app: k8s-git-repo
         version: v0.1
+        release: canary
     spec:
       containers:
       - name: k8s-git-repo
@@ -28,16 +30,47 @@ spec:
         imagePullPolicy: IfNotPresent
         command: 
         - /bin/bash
-        - -xc
+        args:
+        - -c
         - |
-          function clean
-          {
-             echo clean up begun
-             rm -f /home/git/.ssh/*
-             echo clean up done
-          }
+          #!/bin/bash
+          verbose=0
 
-          trap clean EXIT KILL TERM INT
+          # ########################################################
+          # bash signal handlers are executed by docker, but signal
+          # handler [traps] don't appear to be seen by rc delete or
+          # stop in kubernetes v1, commenting for future reference
+          # ########################################################
+
+          # function clean
+          # {
+          #     signal=${1}
+          #     printf "\nSignal ${signal} clean up begun . . . "
+          #     rm -f /home/git/.ssh/*
+          #     printf "done.\n"
+          #     exit 0
+          # }
+
+          # function setup-traps
+          # {
+          #     wrap="$1" ; shift
+          #     call="$1" ; shift
+          #     for sig ; do
+          #         trap "${wrap} ${call} ${sig}" "${sig}"
+          #     done
+          # }
+
+          # function wrap-trap-func
+          # {
+          #     if ((verbose)); then
+          #         printf "\nTrapped: ${2}. Calling ${1} from signal ${2} "
+          #     fi
+          #     ${1} ${2}
+          # }
+          # # setup by calling wrap with args for the function to call and the
+          # # signal name to trap
+          # setup-traps wrap-trap-func clean EXIT KILL TERM INT HUP ILL QUIT USR1 USR2 SEGV STOP
+
           while [[ ! -e /home/git/.private/authorized-keys ]]; do
               sleep 1;
           done;
@@ -48,10 +81,12 @@ spec:
           pushd /home/git/.ssh/
           for file in /home/git/.private/*; do
               name=${file//-/_}
-              # If the secrets are copied then the dead container
-              # exposes the secret. Since this is a public key, it
-              # might be okay, but for getting into good habits. . .
-              # soft link as the owner
+              #######################################################
+              # If the secrets are copied then the dead container may
+              # expose the secret. Since this is a public key, it
+              # might be okay, but for getting into a good habit soft
+              # link as the owner, leaving it in the secret store.
+              # ######################################################
               su -c "ln -sf ${file} ${name##*/}" git
           done;
           chmod -R 700 /home/git/{.private,.ssh} ;
